name: devops test

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    name: ansible test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v3
      
    - name: Run Ansible playbook
      uses: dawidd6/action-ansible-playbook@v2.8.0
      with:
        # Required, playbook filepath
        playbook: deploy.yml
        # Optional, directory where playbooks live
        directory: ./
        key: ${{secrets.SSH_KEY}}
        inventory: |
          [all]
          54.180.98.36
    
          [group1]
          54.180.98.36
