- name: Run playbook
  uses: dawidd6/action-ansible-playbook@v2
  with:
    # Required, playbook filepath
    playbook: deploy.yml
    # Optional, directory where playbooks live
    directory: ./
    key: ${{secrets.SSH_KEY}}
    inventory: |
      [all]
      54.180.98.36

      [group1]
      54.180.98.36
