name: devops test

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    name: ansible test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Run Ansible playbook
      uses: dawidd6/action-ansible-playbook@v2.8.0
      with:
        # Required, playbook filepath
        playbook: deploy.yml
        # Optional, directory where playbooks live
        directory: ./
        key: ${{secrets.SSH_KEY}}
        inventory: |
          [all]
          3.34.46.247 ansible_ssh_user=ubuntu

    - name: get code from github
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script: |
          sudo rm -rf ./devops
          sudo git clone https://github.com/ddarahakit2023/devops
          sudo mv -f ./devops/*.html /var/www/html
