name: main branch auto ci process script

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: 44.211.130.29
          username: ubuntu
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: 22
          script: | # 실행될 스크립트
            cd /var/www/html/test-project
            git pull
